### ISSUE TITLE
Define the process/requirement for changing the membership document in the future

### ISSUE THREAD

**Issue by Powersource** [scuttlebutt-eu/important-documents#20]

**Comment by Powersource** [comment]
Note: To keep things simple, this process/voting method doesn't have to be the same as whatever we end up using for other general decisions in the consortium. So an ad hoc decision process is fine

**Comment by elavoie** [comment]
See comment here: https://github.com/scuttlebutt-eu/important-documents/pull/26#issuecomment-612879050
