### ISSUE TITLE
Make website 1.0

### ISSUE THREAD

**Issue by staltz** [scuttlebutt-eu/important-documents#35]

**Comment by Powersource** [comment]
@ZELFs I think it's mostly some text left missing now. Of which I think the only required one is to fix up the text on the Home page.

**Comment by Powersource** [comment]
Taking the liberty to close this issue (which is blocking Launch) and opening a new issue that's outside the Launch milestone for fixing up the homepage. I think the text is good enough for announcing the collective to friends, but we should maybe patch it before applying for the next grant :P 

https://github.com/scuttlebutt-eu/important-documents/issues/47

**Comment by Powersource** [comment]
Oh and the link https://scuttlebutt.eu/

**Comment by Powersource** [comment]
And repo https://github.com/scuttlebutt-eu/scuttlebutt-eu.github.io
