### ISSUE TITLE
What's the acronym, ESSBC, EUSSBC?

### ISSUE THREAD

**Issue by Powersource** [scuttlebutt-eu/important-documents#46]
Personally ESSBC but it came up in discussion that we haven't defined this

**Comment by Powersource** [comment]
ESC would be cool but there's already a billion things with that acronym

**Comment by staltz** [comment]
I like EUSSBC

**Comment by Powersource** [comment]
I'd kind of like it too if it wasn't so long, I think ESSBC is already getting pretty silly long :P

**Comment by staltz** [comment]
How about e-ssbc ? Since "ssbc" is a familiar one, and we're just adding `e` in front, but `-` like e-mail.

**Comment by Powersource** [comment]
After a vote:
ESC
